# Generated by Django 2.2.6 on 2019-12-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawling',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('sale', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('img_src', models.URLField()),
                ('detail_guide', models.TextField()),
                ('detail_src', models.TextField(null=True)),
            ],
        ),
    ]
